inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - spec/dummy/**/*
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

RSpec/ExampleLength:
  # default 5
  Max: 12

RSpec/MultipleExpectations:
  # default 1
  Max: 4

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
